### ISSUE TITLE
Write a class to read and parse the custome Game Data

### ISSUE THREAD

**Issue by timrobert** [MetalCowRobotics/Robot2018#41]
2018 introduced custom game data to read the switches and scale on tye field
We need to have a .utils class that reads and parses these data fields somehow.

Dashboard just provides it as a string of 3 char.  We need to make it easier to understand.

Also, we need to use dashboard to read which side red/blue we are on.

**Kids need a printed sketches _playbook_ showing how each auton runs and where it needs to start from**

--Tim

**Comment by timrobert** [comment]
Added categories to ticket

**Comment by deaner8765** [comment]
This is already in mission...the superclass for all autonomous missions
23 	private Hand getNearSwitch() { 
24 		return driverStation.getGameSpecificMessage().toUpperCase().charAt(0) == 'L' ? Hand.kLeft : Hand.kRight; 
25 	} 
26 
 
27 	private Hand getScale() { 
28 		return driverStation.getGameSpecificMessage().toUpperCase().charAt(1) == 'L' ? Hand.kLeft : Hand.kRight; 
29 	} 
30 
 
31 	private Hand getFarSwitch() { 
32 		return driverStation.getGameSpecificMessage().toUpperCase().charAt(2) == 'L' ? Hand.kLeft : Hand.kRight; 
33 	} 
btw those statements can be simplified to just return without the inline if
